AirDropXContractAddress = "0x9fBb1680138eaC7Af94F58E791c1211aE641C3b8" 
EthApi = "https://ropsten.infura.io/v3/xxxx" 
ExcelFilePath = "./example.xlsx" 
GasLimit = 20 
IncreaseGas = 5 
LogFilePath = "" 
Seed = "0xxxxxxx" 
SheetName = "Winner" # sheet name excel
StartIndex = 0 # start index of address in excel
TokenContractAddress = "0x73d6167A3321856937C8200FF0c990Ef6cb10fE6" 
TransNumberLimit = 50 # token transfer number limit in one transaction
